apiVersion: v1
kind: Namespace
metadata:
  name: CloudOpsBlend
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: CloudOpsBlend
  name: EKS_AutoScaling
spec:
  selector:
    matchLabels:
      app: EKS_AutoScaling
  template:
    metadata: 
      labels:
        app: EKS_AutoScaling
    spec:
      containers:
        - name: myapp
          image: <Image>
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 5001

            
